### ISSUE TITLE
Dynamically create kubectl config

### ISSUE THREAD

**Issue by Jules-7** [Worth-NL/notifications-api#8]
Docker workflow (actions) contains a `kubectl` step, which is necessary to restart API deployment when a new Docker image is built and pushed. 

To properly function, `kubectl` needs a config file:
```
 - name: Install and configure kubectl
   uses: actions-hub/kubectl@master
   env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
```
`KUBE_CONFIG` is a `base64` representation of configuration obtained with: `az aks get-credentials --resource-group dh-notify-rg --name dh-notify-aks`.

Having `KUBE_CONFIG` hardcoded into secrets is not a problem unless the resource group (`dh-notify-rg`) or cluster name (`dh-notify-aks`) change.

In order to avoid having to manually replace the secret (which is not that much work), a step can be added to the workflow to obtain the configuration and update the secret in the repository (for inspiration check this docs https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28).
